/*jslint */
/*global AdobeEdge: false, window: false, document: false, console:false, alert: false */
(function (compId) {

    "use strict";
    var im='images/',
        aud='media/',
        vid='media/',
        js='js/',
        fonts = {
        },
        opts = {
            'gAudioPreloadPreference': 'auto',
            'gVideoPreloadPreference': 'auto'
        },
        resources = [
        ],
        scripts = [
        ],
        symbols = {
            "stage": {
                version: "6.0.0",
                minimumCompatibleVersion: "5.0.0",
                build: "6.0.0.400",
                scaleToFit: "none",
                centerStage: "none",
                resizeInstances: false,
                content: {
                    dom: [
                        {
                            id: 'Escudo_del_sena4',
                            type: 'image',
                            rect: ['-700px', '-324px', '289px', '364px', 'auto', 'auto'],
                            autoOrient: true,
                            fill: ["rgba(0,0,0,0)",im+"Escudo%20del%20sena.png",'0px','0px']
                        },
                        {
                            id: 'logo-CM-transp_1',
                            type: 'image',
                            rect: ['617px', '198px', '512px', '512px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"logo-CM-transp%20%281%29.png",'0px','0px'],
                            transform: [[],['-7']]
                        },
                        {
                            id: 'nio-logo4',
                            type: 'image',
                            rect: ['293px', '-530px', '306px', '170px', 'auto', 'auto'],
                            autoOrient: true,
                            fill: ["rgba(0,0,0,0)",im+"ni%C3%B1o-logo.png",'0px','0px']
                        }
                    ],
                    style: {
                        '${Stage}': {
                            isStage: true,
                            rect: ['null', 'null', '900px', '550px', 'auto', 'auto'],
                            overflow: 'auto',
                            fill: ["rgba(252,255,250,1.00)"]
                        }
                    }
                },
                timeline: {
                    duration: 2000,
                    autoPlay: true,
                    data: [
                        [
                            "eid235",
                            "width",
                            0,
                            250,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '512px',
                            '320px'
                        ],
                        [
                            "eid244",
                            "width",
                            250,
                            610,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '320px',
                            '216px'
                        ],
                        [
                            "eid252",
                            "width",
                            860,
                            440,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '216px',
                            '180px'
                        ],
                        [
                            "eid255",
                            "width",
                            1300,
                            125,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '180px',
                            '217px'
                        ],
                        [
                            "eid258",
                            "width",
                            1425,
                            75,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '217px',
                            '208px'
                        ],
                        [
                            "eid262",
                            "width",
                            1500,
                            105,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '208px',
                            '168px'
                        ],
                        [
                            "eid265",
                            "width",
                            1605,
                            105,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '168px',
                            '228px'
                        ],
                        [
                            "eid268",
                            "width",
                            1710,
                            90,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '228px',
                            '208px'
                        ],
                        [
                            "eid238",
                            "rotateZ",
                            0,
                            750,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '-7deg',
                            '29deg'
                        ],
                        [
                            "eid245",
                            "rotateZ",
                            750,
                            250,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '29deg',
                            '-16deg'
                        ],
                        [
                            "eid248",
                            "rotateZ",
                            1000,
                            150,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '-16deg',
                            '-2deg'
                        ],
                        [
                            "eid266",
                            "rotateZ",
                            1150,
                            650,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '-2deg',
                            '1deg'
                        ],
                        [
                            "eid205",
                            "width",
                            0,
                            920,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '289px',
                            '206px'
                        ],
                        [
                            "eid213",
                            "width",
                            920,
                            330,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '206px',
                            '255px'
                        ],
                        [
                            "eid215",
                            "width",
                            1250,
                            50,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '255px',
                            '196px'
                        ],
                        [
                            "eid217",
                            "width",
                            1300,
                            50,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '196px',
                            '274px'
                        ],
                        [
                            "eid219",
                            "width",
                            1350,
                            75,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '274px',
                            '241px'
                        ],
                        [
                            "eid221",
                            "width",
                            1425,
                            75,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '241px',
                            '219px'
                        ],
                        [
                            "eid223",
                            "width",
                            1500,
                            105,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '219px',
                            '148px'
                        ],
                        [
                            "eid225",
                            "width",
                            1605,
                            105,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '148px',
                            '203px'
                        ],
                        [
                            "eid229",
                            "width",
                            1710,
                            40,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '203px',
                            '208px'
                        ],
                        [
                            "eid297",
                            "location",
                            0,
                            160,
                            "swing",
                            "${nio-logo4}",
                            [[446.33, -409.5, 0, 0, 0, 0,0],[396, -312.83, 0, 0, 0, 0,108.99]]
                        ],
                        [
                            "eid298",
                            "location",
                            160,
                            90,
                            "swing",
                            "${nio-logo4}",
                            [[396.17, -312.99, 0, 0, 0, 0,0],[459.33, -155.83, 0, 0, 0, 0,169.37]]
                        ],
                        [
                            "eid299",
                            "location",
                            250,
                            90,
                            "swing",
                            "${nio-logo4}",
                            [[459, -155.99, 0, 0, 0, 0,0],[412.83, -8.83, 0, 0, 0, 0,154.23]]
                        ],
                        [
                            "eid300",
                            "location",
                            340,
                            305,
                            "swing",
                            "${nio-logo4}",
                            [[413, -8.99, 0, 0, 0, 0,0],[376.33, 68.17, 0, 0, 0, 0,85.43],[429.67, 174.83, 0, 0, 0, 0,204.68]]
                        ],
                        [
                            "eid302",
                            "location",
                            645,
                            215,
                            "swing",
                            "${nio-logo4}",
                            [[429.84, 174.68, 0, 0, 0, 0,0],[436.88, 291.83, 0, 0, 0, 0,117.37]]
                        ],
                        [
                            "eid316",
                            "rotateZ",
                            0,
                            1350,
                            "swing",
                            "${nio-logo4}",
                            '0deg',
                            '31deg'
                        ],
                        [
                            "eid305",
                            "width",
                            0,
                            1000,
                            "swing",
                            "${nio-logo4}",
                            '306px',
                            '503px'
                        ],
                        [
                            "eid309",
                            "width",
                            1000,
                            150,
                            "swing",
                            "${nio-logo4}",
                            '503px',
                            '297px'
                        ],
                        [
                            "eid311",
                            "width",
                            1150,
                            100,
                            "swing",
                            "${nio-logo4}",
                            '297px',
                            '188px'
                        ],
                        [
                            "eid313",
                            "width",
                            1250,
                            50,
                            "swing",
                            "${nio-logo4}",
                            '188px',
                            '286px'
                        ],
                        [
                            "eid315",
                            "width",
                            1300,
                            50,
                            "swing",
                            "${nio-logo4}",
                            '286px',
                            '308px'
                        ],
                        [
                            "eid318",
                            "width",
                            1350,
                            75,
                            "swing",
                            "${nio-logo4}",
                            '308px',
                            '293px'
                        ],
                        [
                            "eid320",
                            "width",
                            1425,
                            75,
                            "swing",
                            "${nio-logo4}",
                            '293px',
                            '254px'
                        ],
                        [
                            "eid321",
                            "width",
                            1500,
                            105,
                            "swing",
                            "${nio-logo4}",
                            '254px',
                            '168px'
                        ],
                        [
                            "eid324",
                            "width",
                            1605,
                            65,
                            "swing",
                            "${nio-logo4}",
                            '168px',
                            '241px'
                        ],
                        [
                            "eid326",
                            "width",
                            1670,
                            330,
                            "swing",
                            "${nio-logo4}",
                            '241px',
                            '220px'
                        ],
                        [
                            "eid304",
                            "height",
                            0,
                            1000,
                            "swing",
                            "${nio-logo4}",
                            '241px',
                            '490px'
                        ],
                        [
                            "eid308",
                            "height",
                            1000,
                            150,
                            "swing",
                            "${nio-logo4}",
                            '490px',
                            '272px'
                        ],
                        [
                            "eid310",
                            "height",
                            1150,
                            100,
                            "swing",
                            "${nio-logo4}",
                            '272px',
                            '239px'
                        ],
                        [
                            "eid312",
                            "height",
                            1250,
                            50,
                            "swing",
                            "${nio-logo4}",
                            '239px',
                            '257px'
                        ],
                        [
                            "eid314",
                            "height",
                            1300,
                            50,
                            "swing",
                            "${nio-logo4}",
                            '257px',
                            '246px'
                        ],
                        [
                            "eid317",
                            "height",
                            1350,
                            75,
                            "swing",
                            "${nio-logo4}",
                            '246px',
                            '173px'
                        ],
                        [
                            "eid319",
                            "height",
                            1425,
                            75,
                            "swing",
                            "${nio-logo4}",
                            '173px',
                            '207px'
                        ],
                        [
                            "eid323",
                            "height",
                            1500,
                            170,
                            "swing",
                            "${nio-logo4}",
                            '207px',
                            '206px'
                        ],
                        [
                            "eid325",
                            "height",
                            1670,
                            330,
                            "swing",
                            "${nio-logo4}",
                            '206px',
                            '170px'
                        ],
                        [
                            "eid234",
                            "height",
                            0,
                            250,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '512px',
                            '304px'
                        ],
                        [
                            "eid241",
                            "height",
                            250,
                            610,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '304px',
                            '215px'
                        ],
                        [
                            "eid251",
                            "height",
                            860,
                            440,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '215px',
                            '216px'
                        ],
                        [
                            "eid253",
                            "height",
                            1300,
                            125,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '216px',
                            '187px'
                        ],
                        [
                            "eid256",
                            "height",
                            1425,
                            75,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '187px',
                            '215px'
                        ],
                        [
                            "eid261",
                            "height",
                            1500,
                            105,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '215px',
                            '212px'
                        ],
                        [
                            "eid263",
                            "height",
                            1605,
                            105,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '212px',
                            '226px'
                        ],
                        [
                            "eid267",
                            "height",
                            1710,
                            90,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '226px',
                            '202px'
                        ],
                        [
                            "eid273",
                            "background-color",
                            0,
                            160,
                            "swing",
                            "${Stage}",
                            'rgba(255,255,255,1)',
                            'rgba(233,193,249,1.00)'
                        ],
                        [
                            "eid274",
                            "background-color",
                            160,
                            90,
                            "swing",
                            "${Stage}",
                            'rgba(233,193,249,1)',
                            'rgba(215,193,249,1.00)'
                        ],
                        [
                            "eid275",
                            "background-color",
                            250,
                            90,
                            "swing",
                            "${Stage}",
                            'rgba(215,193,249,1)',
                            'rgba(193,210,249,1.00)'
                        ],
                        [
                            "eid276",
                            "background-color",
                            340,
                            60,
                            "swing",
                            "${Stage}",
                            'rgba(193,210,249,1)',
                            'rgba(193,249,247,1.00)'
                        ],
                        [
                            "eid277",
                            "background-color",
                            400,
                            100,
                            "swing",
                            "${Stage}",
                            'rgba(193,249,247,1)',
                            'rgba(193,249,214,1.00)'
                        ],
                        [
                            "eid278",
                            "background-color",
                            500,
                            70,
                            "swing",
                            "${Stage}",
                            'rgba(193,249,214,1)',
                            'rgba(205,249,193,1.00)'
                        ],
                        [
                            "eid279",
                            "background-color",
                            570,
                            75,
                            "swing",
                            "${Stage}",
                            'rgba(205,249,193,1)',
                            'rgba(233,249,193,1.00)'
                        ],
                        [
                            "eid280",
                            "background-color",
                            645,
                            105,
                            "swing",
                            "${Stage}",
                            'rgba(233,249,193,1)',
                            'rgba(249,245,193,1.00)'
                        ],
                        [
                            "eid281",
                            "background-color",
                            750,
                            110,
                            "swing",
                            "${Stage}",
                            'rgba(249,245,193,1)',
                            'rgba(249,247,193,1.00)'
                        ],
                        [
                            "eid282",
                            "background-color",
                            860,
                            60,
                            "swing",
                            "${Stage}",
                            'rgba(249,247,193,1)',
                            'rgba(249,219,193,1.00)'
                        ],
                        [
                            "eid283",
                            "background-color",
                            920,
                            80,
                            "swing",
                            "${Stage}",
                            'rgba(249,219,193,1)',
                            'rgba(249,193,193,1.00)'
                        ],
                        [
                            "eid284",
                            "background-color",
                            1000,
                            70,
                            "swing",
                            "${Stage}",
                            'rgba(249,193,193,1)',
                            'rgba(252,215,215,1.00)'
                        ],
                        [
                            "eid285",
                            "background-color",
                            1070,
                            80,
                            "swing",
                            "${Stage}",
                            'rgba(252,215,215,1)',
                            'rgba(255,235,235,1.00)'
                        ],
                        [
                            "eid286",
                            "background-color",
                            1150,
                            45,
                            "swing",
                            "${Stage}",
                            'rgba(255,235,235,1)',
                            'rgba(255,244,244,1.00)'
                        ],
                        [
                            "eid287",
                            "background-color",
                            1195,
                            55,
                            "swing",
                            "${Stage}",
                            'rgba(255,244,244,1)',
                            'rgba(252,255,250,1.00)'
                        ],
                        [
                            "eid230",
                            "left",
                            0,
                            160,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '1520px',
                            '1352px'
                        ],
                        [
                            "eid232",
                            "left",
                            160,
                            90,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '1352px',
                            '859px'
                        ],
                        [
                            "eid236",
                            "left",
                            250,
                            190,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '859px',
                            '819px'
                        ],
                        [
                            "eid237",
                            "left",
                            440,
                            205,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '819px',
                            '759px'
                        ],
                        [
                            "eid239",
                            "left",
                            645,
                            105,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '759px',
                            '675px'
                        ],
                        [
                            "eid243",
                            "left",
                            750,
                            110,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '675px',
                            '660px'
                        ],
                        [
                            "eid246",
                            "left",
                            860,
                            290,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '660px',
                            '612px'
                        ],
                        [
                            "eid249",
                            "left",
                            1150,
                            150,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '612px',
                            '628px'
                        ],
                        [
                            "eid257",
                            "left",
                            1300,
                            200,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '628px',
                            '629px'
                        ],
                        [
                            "eid259",
                            "left",
                            1500,
                            105,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '629px',
                            '601px'
                        ],
                        [
                            "eid269",
                            "left",
                            1605,
                            195,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '601px',
                            '617px'
                        ],
                        [
                            "eid271",
                            "left",
                            1800,
                            140,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '617px',
                            '577px'
                        ],
                        [
                            "eid293",
                            "left",
                            1940,
                            60,
                            "swing",
                            "${logo-CM-transp_1}",
                            '577px',
                            '580px'
                        ],
                        [
                            "eid231",
                            "top",
                            0,
                            160,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '-12px',
                            '-8px'
                        ],
                        [
                            "eid233",
                            "top",
                            160,
                            90,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '-8px',
                            '128px'
                        ],
                        [
                            "eid240",
                            "top",
                            250,
                            500,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '128px',
                            '123px'
                        ],
                        [
                            "eid242",
                            "top",
                            750,
                            110,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '123px',
                            '181px'
                        ],
                        [
                            "eid247",
                            "top",
                            860,
                            290,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '181px',
                            '168px'
                        ],
                        [
                            "eid250",
                            "top",
                            1150,
                            150,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '168px',
                            '173px'
                        ],
                        [
                            "eid254",
                            "top",
                            1300,
                            125,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '173px',
                            '201px'
                        ],
                        [
                            "eid260",
                            "top",
                            1425,
                            180,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '201px',
                            '177px'
                        ],
                        [
                            "eid264",
                            "top",
                            1605,
                            105,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '177px',
                            '176px'
                        ],
                        [
                            "eid272",
                            "top",
                            1800,
                            140,
                            "easeInQuad",
                            "${logo-CM-transp_1}",
                            '176px',
                            '174px'
                        ],
                        [
                            "eid294",
                            "top",
                            1940,
                            60,
                            "swing",
                            "${logo-CM-transp_1}",
                            '174px',
                            '176px'
                        ],
                        [
                            "eid200",
                            "rotateZ",
                            0,
                            250,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '0deg',
                            '36deg'
                        ],
                        [
                            "eid202",
                            "rotateZ",
                            250,
                            150,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '36deg',
                            '54deg'
                        ],
                        [
                            "eid227",
                            "rotateZ",
                            400,
                            1310,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '54deg',
                            '46deg'
                        ],
                        [
                            "eid198",
                            "location",
                            0,
                            160,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            [[-555.5, -142, 0, 0, 0, 0,0],[-435.5, 131, 0, 0, 0, 0,298.21]]
                        ],
                        [
                            "eid199",
                            "location",
                            160,
                            90,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            [[-435.5, 131, 0, 0, 0, 0,0],[-347.5, 182, 0, 0, 0, 0,101.71]]
                        ],
                        [
                            "eid201",
                            "location",
                            250,
                            150,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            [[-347.5, 182, 0, 0, 0, 0,0],[-135.5, 234, 0, 0, 0, 0,218.28]]
                        ],
                        [
                            "eid203",
                            "location",
                            400,
                            350,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            [[-135.5, 234, 0, 0, 0, 0,0],[-47.5, 249.74, 0, 0, 0, 0,89.4]]
                        ],
                        [
                            "eid207",
                            "location",
                            750,
                            250,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            [[-47.5, 249.74, 0, 0, 0, 0,0],[-7, 262.01, 0, 0, 0, 0,42.32]]
                        ],
                        [
                            "eid209",
                            "location",
                            1000,
                            70,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            [[-7, 262.01, 0, 0, 0, 0,0],[33, 262.01, 0, 0, 0, 0,40]]
                        ],
                        [
                            "eid210",
                            "location",
                            1070,
                            80,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            [[33, 262.01, 0, 0, 0, 0,0],[81, 258.5, 0, 0, 0, 0,48.13]]
                        ],
                        [
                            "eid211",
                            "location",
                            1150,
                            45,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            [[81, 258.5, 0, 0, 0, 0,0],[117, 259.26, 0, 0, 0, 0,36.01]]
                        ],
                        [
                            "eid226",
                            "location",
                            1195,
                            515,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            [[117, 259.26, 0, 0, 0, 0,0],[165.5, 276.98, 0, 0, 0, 0,51.64]]
                        ],
                        [
                            "eid204",
                            "height",
                            0,
                            920,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '364px',
                            '241px'
                        ],
                        [
                            "eid212",
                            "height",
                            920,
                            330,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '241px',
                            '282px'
                        ],
                        [
                            "eid214",
                            "height",
                            1250,
                            50,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '282px',
                            '291px'
                        ],
                        [
                            "eid216",
                            "height",
                            1300,
                            50,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '291px',
                            '298px'
                        ],
                        [
                            "eid218",
                            "height",
                            1350,
                            75,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '298px',
                            '216px'
                        ],
                        [
                            "eid220",
                            "height",
                            1425,
                            75,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '216px',
                            '244px'
                        ],
                        [
                            "eid222",
                            "height",
                            1500,
                            105,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '244px',
                            '230px'
                        ],
                        [
                            "eid224",
                            "height",
                            1605,
                            105,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '230px',
                            '241px'
                        ],
                        [
                            "eid228",
                            "height",
                            1710,
                            40,
                            "easeInQuad",
                            "${Escudo_del_sena4}",
                            '241px',
                            '249px'
                        ]
                    ]
                }
            }
        };

    AdobeEdge.registerCompositionDefn(compId, symbols, fonts, scripts, resources, opts);

    if (!window.edge_authoring_mode) AdobeEdge.getComposition(compId).load("animate0_edgeActions.js");
})("EDGE-3612019");
