/*jslint */
/*global AdobeEdge: false, window: false, document: false, console:false, alert: false */
(function (compId) {

    "use strict";
    var im='images/',
        aud='media/',
        vid='media/',
        js='js/',
        fonts = {
        },
        opts = {
            'gAudioPreloadPreference': 'auto',
            'gVideoPreloadPreference': 'auto'
        },
        resources = [
        ],
        scripts = [
        ],
        symbols = {
            "stage": {
                version: "6.0.0",
                minimumCompatibleVersion: "5.0.0",
                build: "6.0.0.400",
                scaleToFit: "none",
                centerStage: "none",
                resizeInstances: false,
                content: {
                    dom: [
                        {
                            id: 'logo-CM-transp_1',
                            type: 'image',
                            rect: ['1750px', '-50px', '512px', '512px', 'auto', 'auto'],
                            autoOrient: true,
                            fill: ["rgba(0,0,0,0)",im+"logo-CM-transp%20%281%29.png",'0px','0px'],
                            transform: [[],['-24']]
                        },
                        {
                            id: 'nio-logo',
                            type: 'image',
                            rect: ['458px', '-417px', '353px', '273px', 'auto', 'auto'],
                            autoOrient: true,
                            fill: ["rgba(0,0,0,0)",im+"ni%C3%B1o-logo.png",'0px','0px']
                        },
                        {
                            id: 'letra',
                            type: 'image',
                            rect: ['350px', '858px', '665px', '71px', 'auto', 'auto'],
                            autoOrient: true,
                            fill: ["rgba(0,0,0,0)",im+"letra.png",'0px','0px'],
                            transform: [[],['4']]
                        },
                        {
                            id: 'Escudo_del_sena',
                            type: 'image',
                            rect: ['-693px', '5px', '276px', '353px', 'auto', 'auto'],
                            autoOrient: true,
                            fill: ["rgba(0,0,0,0)",im+"Escudo%20del%20sena.png",'0px','0px']
                        },
                        {
                            id: 'Rectangle',
                            type: 'rect',
                            rect: ['0px', '5px', '468px', '49px', 'auto', 'auto'],
                            fill: ["rgba(192,192,192,1)"],
                            stroke: [0,"rgba(0,0,0,1)","none"]
                        },
                        {
                            id: 'RectangleCopy',
                            type: 'rect',
                            rect: ['1840px', '258px', '468px', '49px', 'auto', 'auto'],
                            fill: ["rgba(227,224,224,1.00)"],
                            stroke: [0,"rgba(0,0,0,1)","none"]
                        },
                        {
                            id: 'RectangleCopy2',
                            type: 'rect',
                            rect: ['0px', '77px', '468px', '49px', 'auto', 'auto'],
                            fill: ["rgba(192,192,192,1)"],
                            stroke: [0,"rgba(0,0,0,1)","none"]
                        }
                    ],
                    style: {
                        '${Stage}': {
                            isStage: true,
                            rect: [undefined, undefined, '100%', '116.9%'],
                            overflow: 'hidden',
                            fill: ["rgba(255,255,255,1)"]
                        }
                    }
                },
                timeline: {
                    duration: 2000,
                    autoPlay: true,
                    data: [
                        [
                            "eid106",
                            "top",
                            500,
                            250,
                            "linear",
                            "${RectangleCopy2}",
                            '5px',
                            '77px'
                        ],
                        [
                            "eid23",
                            "height",
                            0,
                            1500,
                            "linear",
                            "${logo-CM-transp_1}",
                            '512px',
                            '318px'
                        ],
                        [
                            "eid25",
                            "height",
                            1500,
                            45,
                            "linear",
                            "${logo-CM-transp_1}",
                            '318px',
                            '400px'
                        ],
                        [
                            "eid27",
                            "height",
                            1545,
                            60,
                            "linear",
                            "${logo-CM-transp_1}",
                            '400px',
                            '479px'
                        ],
                        [
                            "eid29",
                            "height",
                            1605,
                            50,
                            "linear",
                            "${logo-CM-transp_1}",
                            '479px',
                            '338px'
                        ],
                        [
                            "eid31",
                            "height",
                            1655,
                            95,
                            "linear",
                            "${logo-CM-transp_1}",
                            '338px',
                            '459px'
                        ],
                        [
                            "eid35",
                            "height",
                            1750,
                            175,
                            "linear",
                            "${logo-CM-transp_1}",
                            '459px',
                            '296px'
                        ],
                        [
                            "eid48",
                            "width",
                            0,
                            1500,
                            "linear",
                            "${nio-logo}",
                            '420px',
                            '338px'
                        ],
                        [
                            "eid50",
                            "width",
                            1500,
                            105,
                            "linear",
                            "${nio-logo}",
                            '338px',
                            '345px'
                        ],
                        [
                            "eid52",
                            "width",
                            1605,
                            50,
                            "linear",
                            "${nio-logo}",
                            '345px',
                            '353px'
                        ],
                        [
                            "eid11",
                            "location",
                            0,
                            250,
                            "linear",
                            "${logo-CM-transp_1}",
                            [[2006, 206, 0, 0, 0, 0,0],[1829.75, 263.5, 0, 0, 0, 0,185.39]]
                        ],
                        [
                            "eid18",
                            "location",
                            250,
                            290,
                            "linear",
                            "${logo-CM-transp_1}",
                            [[1829.75, 263.5, 0, 0, 0, 0,0],[1645.58, 262.25, 0, 0, 0, 0,184.17]]
                        ],
                        [
                            "eid19",
                            "location",
                            540,
                            210,
                            "linear",
                            "${logo-CM-transp_1}",
                            [[1645.58, 262.25, 0, 0, 0, 0,0],[1475.25, 288.92, 0, 0, 0, 0,172.41]]
                        ],
                        [
                            "eid20",
                            "location",
                            750,
                            170,
                            "linear",
                            "${logo-CM-transp_1}",
                            [[1475.25, 288.92, 0, 0, 0, 0,0],[1366.5, 313.83, -106.32, 29.2, -97.69, 26.83,111.58]]
                        ],
                        [
                            "eid21",
                            "location",
                            920,
                            330,
                            "linear",
                            "${logo-CM-transp_1}",
                            [[1366.5, 313.83, 0, 0, 0, 0,0],[1139, 339.33, 0, 0, 0, 0,228.92]]
                        ],
                        [
                            "eid22",
                            "location",
                            1250,
                            250,
                            "linear",
                            "${logo-CM-transp_1}",
                            [[1139, 339.33, 0, 0, 0, 0,0],[1071.18, 332.33, 0, 0, 0, 0,68.18]]
                        ],
                        [
                            "eid24",
                            "width",
                            0,
                            1500,
                            "linear",
                            "${logo-CM-transp_1}",
                            '512px',
                            '480px'
                        ],
                        [
                            "eid26",
                            "width",
                            1500,
                            45,
                            "linear",
                            "${logo-CM-transp_1}",
                            '480px',
                            '466px'
                        ],
                        [
                            "eid28",
                            "width",
                            1545,
                            60,
                            "linear",
                            "${logo-CM-transp_1}",
                            '466px',
                            '423px'
                        ],
                        [
                            "eid30",
                            "width",
                            1605,
                            50,
                            "linear",
                            "${logo-CM-transp_1}",
                            '423px',
                            '402px'
                        ],
                        [
                            "eid32",
                            "width",
                            1655,
                            95,
                            "linear",
                            "${logo-CM-transp_1}",
                            '402px',
                            '500px'
                        ],
                        [
                            "eid36",
                            "width",
                            1750,
                            175,
                            "linear",
                            "${logo-CM-transp_1}",
                            '500px',
                            '310px'
                        ],
                        [
                            "eid34",
                            "rotateZ",
                            0,
                            1845,
                            "linear",
                            "${logo-CM-transp_1}",
                            '0deg',
                            '-18deg'
                        ],
                        [
                            "eid39",
                            "rotateZ",
                            1845,
                            80,
                            "linear",
                            "${logo-CM-transp_1}",
                            '-18deg',
                            '-24deg'
                        ],
                        [
                            "eid107",
                            "left",
                            500,
                            250,
                            "linear",
                            "${RectangleCopy2}",
                            '0px',
                            '3290px'
                        ],
                        [
                            "eid88",
                            "rotateZ",
                            0,
                            1500,
                            "linear",
                            "${Escudo_del_sena}",
                            '0deg',
                            '-1deg'
                        ],
                        [
                            "eid67",
                            "width",
                            0,
                            1605,
                            "linear",
                            "${letra}",
                            '665px',
                            '358px'
                        ],
                        [
                            "eid69",
                            "width",
                            1605,
                            50,
                            "linear",
                            "${letra}",
                            '358px',
                            '429px'
                        ],
                        [
                            "eid47",
                            "height",
                            0,
                            1500,
                            "linear",
                            "${nio-logo}",
                            '331px',
                            '220px'
                        ],
                        [
                            "eid49",
                            "height",
                            1500,
                            105,
                            "linear",
                            "${nio-logo}",
                            '220px',
                            '360px'
                        ],
                        [
                            "eid51",
                            "height",
                            1605,
                            50,
                            "linear",
                            "${nio-logo}",
                            '360px',
                            '273px'
                        ],
                        [
                            "eid108",
                            "height",
                            0,
                            750,
                            "linear",
                            "${RectangleCopy2}",
                            '49px',
                            '17px'
                        ],
                        [
                            "eid76",
                            "height",
                            0,
                            920,
                            "linear",
                            "${Escudo_del_sena}",
                            '331px',
                            '231px'
                        ],
                        [
                            "eid78",
                            "height",
                            920,
                            150,
                            "linear",
                            "${Escudo_del_sena}",
                            '231px',
                            '373px'
                        ],
                        [
                            "eid81",
                            "height",
                            1070,
                            80,
                            "linear",
                            "${Escudo_del_sena}",
                            '373px',
                            '246px'
                        ],
                        [
                            "eid83",
                            "height",
                            1150,
                            100,
                            "linear",
                            "${Escudo_del_sena}",
                            '246px',
                            '412px'
                        ],
                        [
                            "eid85",
                            "height",
                            1250,
                            135,
                            "linear",
                            "${Escudo_del_sena}",
                            '412px',
                            '353px'
                        ],
                        [
                            "eid89",
                            "height",
                            1385,
                            365,
                            "linear",
                            "${Escudo_del_sena}",
                            '353px',
                            '390px'
                        ],
                        [
                            "eid91",
                            "height",
                            1750,
                            135,
                            "linear",
                            "${Escudo_del_sena}",
                            '390px',
                            '356px'
                        ],
                        [
                            "eid75",
                            "location",
                            0,
                            250,
                            "linear",
                            "${Escudo_del_sena}",
                            [[-554.5, 170.5, 0, 0, 0, 0,0],[105.5, 290.5, 0, 0, 0, 0,670.82]]
                        ],
                        [
                            "eid80",
                            "location",
                            250,
                            900,
                            "linear",
                            "${Escudo_del_sena}",
                            [[105.5, 290.5, 0, 0, 0, 0,0],[225.5, 290.5, 0, 0, 0, 0,120]]
                        ],
                        [
                            "eid87",
                            "location",
                            1150,
                            235,
                            "linear",
                            "${Escudo_del_sena}",
                            [[225.5, 290.5, 0, 0, 0, 0,0],[276, 301, 0, 0, 0, 0,51.58]]
                        ],
                        [
                            "eid120",
                            "height",
                            0,
                            1500,
                            "linear",
                            "${RectangleCopy}",
                            '49px',
                            '69px'
                        ],
                        [
                            "eid119",
                            "width",
                            0,
                            1500,
                            "linear",
                            "${RectangleCopy}",
                            '468px',
                            '208px'
                        ],
                        [
                            "eid37",
                            "height",
                            0,
                            1925,
                            "linear",
                            "${Stage}",
                            '116.89%',
                            '100%'
                        ],
                        [
                            "eid77",
                            "width",
                            0,
                            920,
                            "linear",
                            "${Escudo_del_sena}",
                            '277px',
                            '297px'
                        ],
                        [
                            "eid79",
                            "width",
                            920,
                            150,
                            "linear",
                            "${Escudo_del_sena}",
                            '297px',
                            '317px'
                        ],
                        [
                            "eid82",
                            "width",
                            1070,
                            80,
                            "linear",
                            "${Escudo_del_sena}",
                            '317px',
                            '279px'
                        ],
                        [
                            "eid84",
                            "width",
                            1150,
                            100,
                            "linear",
                            "${Escudo_del_sena}",
                            '279px',
                            '188px'
                        ],
                        [
                            "eid86",
                            "width",
                            1250,
                            135,
                            "linear",
                            "${Escudo_del_sena}",
                            '188px',
                            '276px'
                        ],
                        [
                            "eid90",
                            "width",
                            1385,
                            365,
                            "linear",
                            "${Escudo_del_sena}",
                            '276px',
                            '308px'
                        ],
                        [
                            "eid92",
                            "width",
                            1750,
                            135,
                            "linear",
                            "${Escudo_del_sena}",
                            '308px',
                            '278px'
                        ],
                        [
                            "eid71",
                            "rotateZ",
                            0,
                            1750,
                            "linear",
                            "${letra}",
                            '0deg',
                            '4deg'
                        ],
                        [
                            "eid42",
                            "location",
                            0,
                            250,
                            "linear",
                            "${nio-logo}",
                            [[668, -251.5, 0, 0, 0, 0,0],[666, -202.5, 0, 0, 0, 0,49.04]]
                        ],
                        [
                            "eid43",
                            "location",
                            250,
                            250,
                            "linear",
                            "${nio-logo}",
                            [[666, -202.5, 0, 0, 0, 0,0],[683, -160.5, 0, 0, 0, 0,45.31]]
                        ],
                        [
                            "eid44",
                            "location",
                            500,
                            185,
                            "linear",
                            "${nio-logo}",
                            [[683, -160.5, 0, 0, 0, 0,0],[675, -28.5, 0, 0, 0, 0,132.24]]
                        ],
                        [
                            "eid45",
                            "location",
                            685,
                            235,
                            "linear",
                            "${nio-logo}",
                            [[675, -28.5, 0, 0, 0, 0,0],[683.23, 144.39, 0, 0, 0, 0,173.08]]
                        ],
                        [
                            "eid46",
                            "location",
                            920,
                            275,
                            "linear",
                            "${nio-logo}",
                            [[683.23, 144.39, 0, 0, 0, 0,0],[673, 312.5, 0, 0, 0, 0,168.42]]
                        ],
                        [
                            "eid147",
                            "background-color",
                            750,
                            170,
                            "linear",
                            "${RectangleCopy}",
                            'rgba(227,224,224,1)',
                            'rgba(150,150,150,1.00)'
                        ],
                        [
                            "eid148",
                            "background-color",
                            920,
                            230,
                            "linear",
                            "${RectangleCopy}",
                            'rgba(150,150,150,1)',
                            'rgba(197,197,197,1.00)'
                        ],
                        [
                            "eid149",
                            "background-color",
                            1150,
                            350,
                            "linear",
                            "${RectangleCopy}",
                            'rgba(197,197,197,1)',
                            'rgba(159,159,159,1.00)'
                        ],
                        [
                            "eid105",
                            "top",
                            0,
                            250,
                            "linear",
                            "${RectangleCopy}",
                            '5px',
                            '45px'
                        ],
                        [
                            "eid110",
                            "top",
                            250,
                            500,
                            "linear",
                            "${RectangleCopy}",
                            '45px',
                            '635px'
                        ],
                        [
                            "eid112",
                            "top",
                            750,
                            170,
                            "linear",
                            "${RectangleCopy}",
                            '635px',
                            '612px'
                        ],
                        [
                            "eid113",
                            "top",
                            920,
                            230,
                            "linear",
                            "${RectangleCopy}",
                            '612px',
                            '361px'
                        ],
                        [
                            "eid115",
                            "top",
                            1150,
                            150,
                            "linear",
                            "${RectangleCopy}",
                            '361px',
                            '468px'
                        ],
                        [
                            "eid117",
                            "top",
                            1300,
                            200,
                            "linear",
                            "${RectangleCopy}",
                            '468px',
                            '258px'
                        ],
                        [
                            "eid121",
                            "top",
                            1500,
                            250,
                            "linear",
                            "${RectangleCopy}",
                            '258px',
                            '458px'
                        ],
                        [
                            "eid124",
                            "top",
                            1750,
                            135,
                            "linear",
                            "${RectangleCopy}",
                            '458px',
                            '94px'
                        ],
                        [
                            "eid126",
                            "top",
                            1885,
                            115,
                            "linear",
                            "${RectangleCopy}",
                            '94px',
                            '588px'
                        ],
                        [
                            "eid1",
                            "background-color",
                            0,
                            290,
                            "linear",
                            "${Stage}",
                            'rgba(255,255,255,1)',
                            'rgba(179,179,179,1.00)'
                        ],
                        [
                            "eid2",
                            "background-color",
                            290,
                            250,
                            "linear",
                            "${Stage}",
                            'rgba(179,179,179,1.00)',
                            'rgba(212,212,212,1.00)'
                        ],
                        [
                            "eid5",
                            "background-color",
                            540,
                            210,
                            "linear",
                            "${Stage}",
                            'rgba(212,212,212,1.00)',
                            'rgba(216,216,216,1.00)'
                        ],
                        [
                            "eid3",
                            "background-color",
                            750,
                            250,
                            "linear",
                            "${Stage}",
                            'rgba(216,216,216,1.00)',
                            'rgba(236,236,236,1.00)'
                        ],
                        [
                            "eid6",
                            "background-color",
                            1000,
                            250,
                            "linear",
                            "${Stage}",
                            'rgba(236,236,236,1.00)',
                            'rgba(237,237,237,1.00)'
                        ],
                        [
                            "eid4",
                            "background-color",
                            1250,
                            250,
                            "linear",
                            "${Stage}",
                            'rgba(237,237,237,1.00)',
                            'rgba(249,249,249,1.00)'
                        ],
                        [
                            "eid8",
                            "background-color",
                            1500,
                            250,
                            "linear",
                            "${Stage}",
                            'rgba(249,249,249,1.00)',
                            'rgba(255,255,255,1.00)'
                        ],
                        [
                            "eid7",
                            "background-color",
                            2000,
                            0,
                            "linear",
                            "${Stage}",
                            'rgba(255,255,255,1.00)',
                            'rgba(255,255,255,1.00)'
                        ],
                        [
                            "eid104",
                            "left",
                            0,
                            250,
                            "linear",
                            "${RectangleCopy}",
                            '0px',
                            '3290px'
                        ],
                        [
                            "eid109",
                            "left",
                            250,
                            500,
                            "linear",
                            "${RectangleCopy}",
                            '3290px',
                            '1450px'
                        ],
                        [
                            "eid111",
                            "left",
                            750,
                            170,
                            "linear",
                            "${RectangleCopy}",
                            '1450px',
                            '-660px'
                        ],
                        [
                            "eid114",
                            "left",
                            920,
                            230,
                            "linear",
                            "${RectangleCopy}",
                            '-660px',
                            '1640px'
                        ],
                        [
                            "eid116",
                            "left",
                            1150,
                            150,
                            "linear",
                            "${RectangleCopy}",
                            '1640px',
                            '-670px'
                        ],
                        [
                            "eid118",
                            "left",
                            1300,
                            200,
                            "linear",
                            "${RectangleCopy}",
                            '-670px',
                            '1840px'
                        ],
                        [
                            "eid122",
                            "left",
                            1500,
                            250,
                            "linear",
                            "${RectangleCopy}",
                            '1840px',
                            '-460px'
                        ],
                        [
                            "eid123",
                            "left",
                            1750,
                            135,
                            "linear",
                            "${RectangleCopy}",
                            '-460px',
                            '1790px'
                        ],
                        [
                            "eid125",
                            "left",
                            1885,
                            115,
                            "linear",
                            "${RectangleCopy}",
                            '1790px',
                            '-590px'
                        ],
                        [
                            "eid102",
                            "top",
                            0,
                            250,
                            "linear",
                            "${Rectangle}",
                            '5px',
                            '15px'
                        ],
                        [
                            "eid55",
                            "location",
                            0,
                            685,
                            "linear",
                            "${letra}",
                            [[682.5, 905, 0, 0, 0, 0,0],[688.5, 821, 0, 0, 0, 0,84.21]]
                        ],
                        [
                            "eid56",
                            "location",
                            685,
                            315,
                            "linear",
                            "${letra}",
                            [[688.5, 821, 0, 0, 0, 0,0],[688.5, 685, 0, 0, 0, 0,136]]
                        ],
                        [
                            "eid65",
                            "location",
                            1000,
                            605,
                            "linear",
                            "${letra}",
                            [[688.5, 685, 0, 0, 0, 0,0],[675, 595.57, 0, 0, 0, 0,90.44]]
                        ],
                        [
                            "eid70",
                            "location",
                            1605,
                            145,
                            "linear",
                            "${letra}",
                            [[675, 595.57, 0, 0, 0, 0,0],[675.5, 502.85, 0, 0, 0, 0,92.72]]
                        ],
                        [
                            "eid53",
                            "rotateZ",
                            0,
                            1655,
                            "linear",
                            "${nio-logo}",
                            '0deg',
                            '-1deg'
                        ],
                        [
                            "eid66",
                            "height",
                            0,
                            1605,
                            "linear",
                            "${letra}",
                            '94px',
                            '98px'
                        ],
                        [
                            "eid68",
                            "height",
                            1605,
                            50,
                            "linear",
                            "${letra}",
                            '98px',
                            '67px'
                        ],
                        [
                            "eid72",
                            "height",
                            1655,
                            95,
                            "linear",
                            "${letra}",
                            '67px',
                            '71px'
                        ],
                        [
                            "eid103",
                            "left",
                            0,
                            250,
                            "linear",
                            "${Rectangle}",
                            '0px',
                            '-870px'
                        ]
                    ]
                }
            }
        };

    AdobeEdge.registerCompositionDefn(compId, symbols, fonts, scripts, resources, opts);

    if (!window.edge_authoring_mode) AdobeEdge.getComposition(compId).load("Animacion0_edgeActions.js");
})("EDGE-3612019");
